language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 10

install:
  - yarn

script:
  - yarn build
  - yarn lint

deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: 'wvandolah.com'
  skip_cleanup: true
  acl: public_read
  local_dir: public