language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 10

install:
  - yarn global add travis-ci-cloudfront-invalidation
  - yarn

script:
  - yarn build
  - yarn lint

deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: 'wvandolah.com'
  skip_cleanup: true
  acl: public_read
  local_dir: public

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST