version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5

jobs:
  build:
    docker:
      - image: node:18
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - aws-cli/install
      - run: aws --version
      - deploy:
          name: Deploy to S3 and invalidate CloudFront cache
          command: |
            aws s3 sync public/ s3://wvandolah.com --delete
            aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DIST_ID --paths "/*"

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master